from enum import Enum


class ErrorCode(str, Enum):
    DATA_FETCH_FAILED = "DATA_FETCH_FAILED"
    LOW_COVERAGE = "LOW_COVERAGE"
    SOLVER_FALLBACK = "SOLVER_FALLBACK"
    RISK_GATE_BLOCKED = "RISK_GATE_BLOCKED"
    EXECUTION_PRECHECK_FAILED = "EXECUTION_PRECHECK_FAILED"
